name: Waka Readme

on:
  schedule:
    - cron: "* * * * *"
  workflow_dispatch:
jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: ashiqursuperfly/waka-readme-stats@configure-badge-colors
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SHOW_COMMIT: "True"
          COMMIT_BY_ME: "True"
          SHOW_DAYS_OF_WEEK: "True"
          SHOW_LANGUAGE: "True"
          SHOW_OS: "True"
          SHOW_EDITORS: "True"
          SHOW_LINES_OF_CODE: "True"
          SHOW_LANGUAGE_PER_REPO: "False"
          SHOW_LOC_CHART: "False"
          SHOW_SHORT_INFO: "False"
          SHOW_PROJECTS: "False"
          SHOW_TIMEZONE: "True"
          SHOW_PROFILE_VIEWS: "True"
